title: Filipe Fernandes
description: UI Engineer at The AA Ireland and Founder at Choco la Design

email: contato@filipefernandes.com.br

linkedin: http://lnkdin.me/filipesf
github:   http://github.com/filipesf
twitter:  http://twitter.com/filipesf

baseurl: ""
url: "http://filipesf.com"
permalink: articles/:title
port: 7777

markdown: kramdown
highlighter: rouge

sass:
  style: :compressed
