title: Filipe Fernandes
description: Front-end Architect and Founder at Choco la Design

email: contato@filipefernandes.com.br

twitter:  http://twitter.com/filipesf
linkedin: http://linkedin.com/in/filipesf
github:   http://github.com/filipesf

baseurl: ""
url: "http://filipesf.github.io"
permalink: articles/:title
port: 7777

markdown: kramdown
highlighter: pygments

sass:
  style: :compressed
