title: Filipe Fernandes
description: Front-end Architect and Founder at Choco la Design

profile_name: Filipe Fernandes
profile_jobtitle: Front-end Architect
profile_bio: "Hey! My name is Filipe Fernandes, I'm a Front-end Architect crazy about CSS stuff and build simple but powerfull websites."

email: contato@filipefernandes.com.br
twitter:  http://twitter.com/filipesf
linkedin: http://linkedin.com/in/filipesf
github:   http://github.com/filipesf

baseurl: ""
url: "http://filipesf.github.io"

markdown: kramdown

permalink: articles/:title
highlighter: pygments

port: 7777

sass:
  style: :compressed

gems: ["jekyll-timeago"]

jekyll_timeago:
  depth: 1
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: 'Published'
  suffix_future: ''
  prefix_future: 'at'
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'
