title: Filipe Fernandes
description: Front-end Architect and Founder at Choco la Design

email: contato@filipefernandes.com.br

twitter:  http://twitter.com/filipesf
linkedin: http://linkedin.com/in/filipesf
github:   http://github.com/filipesf

baseurl: ""
url: "http://filipesf.github.io"

markdown: kramdown

permalink: articles/:title
highlighter: pygments

port: 7777

sass:
  style: :compressed

gems: [jekyll-timeago]

jekyll_timeago:
  depth: 1
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: ''
  suffix_future: ''
  prefix_future: ''
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'
