title: Filipe Fernandes
description: UI Engineer at The AA Ireland and Founder at Choco la Design

email: me@filipesf.com

linkedin: http://linkedin.com/in/filipesf
github:   http://github.com/filipesf
twitter:  http://twitter.com/filipesf

baseurl: ""
url: "http://filipesf.com"
permalink: articles/:title
port: 7777

markdown: kramdown
highlighter: rouge

sass:
  style: :compressed
